### PR TITLE
[#78] Bumped version for maven plugins to fix build issues

### PR DESCRIPTION
**Pull request by korydraughn**
This PR also bumps the Jargon version for 4.3 compatibility.

### CODE REVIEW

**Comment by trel** [comment]
nice - is this confirmed to talk to 4.3?

**Comment by korydraughn** [comment]
Yes. I pointed it at my post-4.3.0 build and it worked.

**Comment by korydraughn** [comment]
Ready to add the pound?

**Comment by trel** [comment]
up to you - go for it.

**Comment by korydraughn** [comment]
Added #

**Review by trel — APPROVED** [review]
merge it

**Pull request merged**
